import { LiteGraph } from "litegraph.js";
import { ConstList } from "./const";
import { LogVulnerable } from "./log";
import { FilterHasPort } from "./filterHasPort";
import { IPRange } from "./ipRange";
import { FilterNmap } from "./filterNmap";
import { MapStripPorts } from "./mapStripPort";
import { CRTSh } from "./crtSh";
import { MapStripProtocol } from "./mapStripProtocol";
import { MapPrefixSuffix } from "./mapPrefixSuffix";
import { FilterMetasploitCheck } from "./filterMetasploitCheck";
import { LogRaw } from "./logRaw";
import { MapStripPaths } from "./mapStripPath";
import { FilterBurp } from "./filterBurp";
import { Sublist3r } from "./sublist3r";
import { FilterZAP } from "./filterZAP";
import { FilterSqlmap } from "./filterSqlmap";
import { FilterHasProtocol } from "./filterHasProtocol";
import { FilterHasPath } from "./filterHasPath";

LiteGraph.clearRegisteredTypes();
LiteGraph.registerNodeType("overflow/const", ConstList);
LiteGraph.registerNodeType("overflow/log", LogVulnerable);
LiteGraph.registerNodeType("overflow/hasport", FilterHasPort);
LiteGraph.registerNodeType("overflow/iprange", IPRange);
LiteGraph.registerNodeType("overflow/nmap", FilterNmap);
LiteGraph.registerNodeType("overflow/stripports", MapStripPorts);
LiteGraph.registerNodeType("overflow/crtsh", CRTSh);
LiteGraph.registerNodeType("overflow/stripproto", MapStripProtocol);
LiteGraph.registerNodeType("overflow/prefixsuffix", MapPrefixSuffix);
LiteGraph.registerNodeType("overflow/metasploitcheck", FilterMetasploitCheck);
LiteGraph.registerNodeType("overflow/lograw", LogRaw);
LiteGraph.registerNodeType("overflow/strippaths", MapStripPaths);
LiteGraph.registerNodeType("overflow/burp", FilterBurp);
LiteGraph.registerNodeType("overflow/sublist3r", Sublist3r);
LiteGraph.registerNodeType("overflow/zap", FilterZAP);
LiteGraph.registerNodeType("overflow/sqlmap", FilterSqlmap);
LiteGraph.registerNodeType("overflow/hasproto", FilterHasProtocol);
LiteGraph.registerNodeType("overflow/haspath", FilterHasPath);